import xlsx from "xlsx";

const rows = [
  {
    Type: "simple",
    SKU: "HT-001",
    Name: "Claw Hammer 16oz",
    Published: 1,
    Description: "<p>Professional grade <strong>claw hammer</strong> with fiberglass handle. Ideal for framing and general carpentry.</p><table><tr><td>Weight</td><td>16 oz</td></tr><tr><td>Handle</td><td>Fiberglass</td></tr></table>",
    "Regular price": 899,
    "Sale price": 749,
    Stock: 50,
    Categories: "Hand Tools",
    Brand: "Stanley",
    Images: "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?w=400",
    Parent: "",
    "Attribute 1 name": "",
    "Attribute 1 value(s)": "",
    "Attribute 2 name": "",
    "Attribute 2 value(s)": "",
  },
  {
    Type: "simple",
    SKU: "HT-002",
    Name: "Tape Measure 25ft",
    Published: 1,
    Description: "<p>Heavy duty <strong>tape measure</strong> with magnetic tip and auto-lock mechanism.</p>",
    "Regular price": 450,
    "Sale price": 399,
    Stock: 120,
    Categories: "Hand Tools",
    Brand: "DeWalt",
    Images: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=400",
    Parent: "",
    "Attribute 1 name": "",
    "Attribute 1 value(s)": "",
    "Attribute 2 name": "",
    "Attribute 2 value(s)": "",
  },
  {
    Type: "variable",
    SKU: "PT-001",
    Name: "Cordless Drill Machine",
    Published: 1,
    Description: "<p>High-performance <strong>cordless drill</strong> with brushless motor technology.</p><ul><li>Variable speed trigger</li><li>LED work light</li><li>Includes carrying case</li></ul>",
    "Regular price": "",
    "Sale price": "",
    Stock: "",
    Categories: "Power Tools",
    Brand: "Bosch",
    Images: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400",
    Parent: "",
    "Attribute 1 name": "Voltage",
    "Attribute 1 value(s)": "12V, 18V, 20V",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Blue, Red",
  },
  {
    Type: "variation",
    SKU: "PT-001-12V-BLUE",
    Name: "",
    Published: 1,
    Description: "",
    "Regular price": 3500,
    "Sale price": 2999,
    Stock: 25,
    Categories: "",
    Brand: "",
    Images: "",
    Parent: "PT-001",
    "Attribute 1 name": "Voltage",
    "Attribute 1 value(s)": "12V",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Blue",
  },
  {
    Type: "variation",
    SKU: "PT-001-18V-BLUE",
    Name: "",
    Published: 1,
    Description: "",
    "Regular price": 4500,
    "Sale price": 3999,
    Stock: 15,
    Categories: "",
    Brand: "",
    Images: "",
    Parent: "PT-001",
    "Attribute 1 name": "Voltage",
    "Attribute 1 value(s)": "18V",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Blue",
  },
  {
    Type: "variation",
    SKU: "PT-001-20V-RED",
    Name: "",
    Published: 1,
    Description: "",
    "Regular price": 5500,
    "Sale price": 4999,
    Stock: 10,
    Categories: "",
    Brand: "",
    Images: "",
    Parent: "PT-001",
    "Attribute 1 name": "Voltage",
    "Attribute 1 value(s)": "20V",
    "Attribute 2 name": "Color",
    "Attribute 2 value(s)": "Red",
  },
  {
    Type: "simple",
    SKU: "SF-001",
    Name: "Safety Goggles Pro",
    Published: 1,
    Description: "<p>Anti-fog <strong>safety goggles</strong> with UV protection. Meets ANSI Z87.1 standards.</p>",
    "Regular price": 350,
    "Sale price": 299,
    Stock: 200,
    Categories: "Safety Equipment",
    Brand: "3M",
    Images: "https://images.unsplash.com/photo-1583468982228-19f19164aee2?w=400",
    Parent: "",
    "Attribute 1 name": "",
    "Attribute 1 value(s)": "",
    "Attribute 2 name": "",
    "Attribute 2 value(s)": "",
  },
  {
    Type: "simple",
    SKU: "ERR-001",
    Name: "",
    Published: 1,
    Description: "This row should fail because Name is missing",
    "Regular price": 100,
    "Sale price": 50,
    Stock: 10,
    Categories: "Test",
    Brand: "Test",
    Images: "",
    Parent: "",
    "Attribute 1 name": "",
    "Attribute 1 value(s)": "",
    "Attribute 2 name": "",
    "Attribute 2 value(s)": "",
  },
];

const worksheet = xlsx.utils.json_to_sheet(rows);
const workbook = xlsx.utils.book_new();
xlsx.utils.book_append_sheet(workbook, worksheet, "Products");

const outputPath = "./test_import_products.xlsx";
xlsx.writeFile(workbook, outputPath);
console.log("Test Excel file created: " + outputPath);
console.log("   - 3 Simple products (Claw Hammer, Tape Measure, Safety Goggles)");
console.log("   - 1 Variable product (Cordless Drill) with 3 variations");
console.log("   - 1 Error row (missing product name, should fail validation)");
console.log("   - Total: 8 rows");
